In [2]:
import pandas as pd

In [3]:
chicagoDataFrame = pd.read_csv("resources/chicago.csv").dropna(how="all")

chicagoDataFrame.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [4]:
# expand parametresi, bolunen degerler ile listelerin her bir ogesi bir column'a denk gelecek sekilde bir dataframe olusturur
result = chicagoDataFrame['Name'].str.split(',', expand=True)

result.head()

         0              1
0    AARON        ELVIA J
1    AARON      JEFFERY M
2    AARON         KARINA
3    AARON    KIMBERLEI R
4  ABAD JR      VICENTE M

In [5]:
temp = chicagoDataFrame.copy()

temp[['First Name', 'Last Name']] = temp['Name'].str.split(',', expand=True)

temp.drop('Name', axis=1, inplace=True)

temp.head()

,Position Title,Department,Employee Annual Salary,First Name,Last Name
0,WATER RATE TAKER,WATER MGMNT,$90744.00,AARON,ELVIA J
1,POLICE OFFICER,POLICE,$84450.00,AARON,JEFFERY M
2,POLICE OFFICER,POLICE,$84450.00,AARON,KARINA
3,CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,AARON,KIMBERLEI R
4,CIVIL ENGINEER IV,WATER MGMNT,$106836.00,ABAD JR,VICENTE M

In [6]:
# n kac ise, olusan column'lardan n'incisine kadar olan column'lar ile bir dataframe dondurur
chicagoDataFrame["Position Title"].str.split(" ", expand=True, n=2).head()

        0         1          2
0   WATER      RATE      TAKER
1  POLICE   OFFICER       None
2  POLICE   OFFICER       None
3   CHIEF  CONTRACT  EXPEDITER
4   CIVIL  ENGINEER         IV

In [7]:
bigmacDataFrame = pd.read_csv('resources/bigmac.csv', parse_dates=['Date'])

bigmacDataFrame.head()

        Date    Country  Price in US Dollars
0 2016-01-01  Argentina                 2.39
1 2016-01-01  Australia                 3.74
2 2016-01-01     Brazil                 3.35
3 2016-01-01    Britain                 4.22
4 2016-01-01     Canada                 4.14

In [8]:
temp = bigmacDataFrame.copy()

# bir dataframe'de inner ve outer index'ler ayarlanacaksa, unique deger sayisi az olan column outer index olarak seceriz
temp.nunique()

# Date column'unu outer index, Country column'unu inner index olarak ayarlar
temp.set_index(['Date', 'Country'], inplace=True)

In [9]:
# multi index'li bir dataframe'de siralama islemi her index icin kendi icinde yapilir
temp.sort_index(inplace=True)

temp.head()

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76
           Britain                   3.67
           Canada                    3.97

In [10]:
# her satir icin index degeri bir tuple olarak tutulur
temp.index

MultiIndex([('2010-01-01',      'Argentina'),
            ('2010-01-01',      'Australia'),
            ('2010-01-01',         'Brazil'),
            ('2010-01-01',        'Britain'),
            ('2010-01-01',         'Canada'),
            ('2010-01-01',          'Chile'),
            ('2010-01-01',          'China'),
            ('2010-01-01',       'Colombia'),
            ('2010-01-01',     'Costa Rica'),
            ('2010-01-01', 'Czech Republic'),
            ...
            ('2016-01-01',    'Switzerland'),
            ('2016-01-01',         'Taiwan'),
            ('2016-01-01',       'Thailand'),
            ('2016-01-01',         'Turkey'),
            ('2016-01-01',            'UAE'),
            ('2016-01-01',        'Ukraine'),
            ('2016-01-01',  'United States'),
            ('2016-01-01',        'Uruguay'),
            ('2016-01-01',      'Venezuela'),
            ('2016-01-01',        'Vietnam')],
           names=['Date', 'Country'], length=652)

In [11]:
# index isimlerinden bir FrozenList nesnesi dondurur
temp.index.names

FrozenList(['Date', 'Country'])

In [12]:
bigmacDataFrame = pd.read_csv('resources/bigmac.csv', parse_dates=['Date'], index_col=['Date', 'Country'])

In [13]:
# asagidaki kod parcalarinin ikisi de outer index olan Date column'unun her satir icin degerlerini iceren bir nesne dondurur
bigmacDataFrame.index.get_level_values('Date')
bigmacDataFrame.index.get_level_values(0)

DatetimeIndex(['2016-01-01', '2016-01-01', '2016-01-01', '2016-01-01',
               '2016-01-01', '2016-01-01', '2016-01-01', '2016-01-01',
               '2016-01-01', '2016-01-01',
               ...
               '2010-01-01', '2010-01-01', '2010-01-01', '2010-01-01',
               '2010-01-01', '2010-01-01', '2010-01-01', '2010-01-01',
               '2010-01-01', '2010-01-01'],
              dtype='datetime64[ns]', name='Date', length=652, freq=None)

In [14]:
# index column'larimin adlarini degirtirir
bigmacDataFrame.index.set_names(names=['Day', 'Location'], inplace=True)

# sadece belirtilen index column'unun adini degistirir
bigmacDataFrame.index.set_names(names='Date', level=0, inplace=True)

bigmacDataFrame.head()

                      Price in US Dollars
Date       Location
2016-01-01 Argentina                 2.39
           Australia                 3.74
           Brazil                    3.35
           Britain                   4.22
           Canada                    4.14

In [15]:
# index column'larini kendi icinde siralar, ascending=True (varsayilan) artan siralama, ascending=False azalan siralama
# iki column icin de azalan siralama yapar
bigmacDataFrame.sort_index(ascending=False)

# ilk index column icin artan siralama, ikinci index column icin azalan siralama yapar
bigmacDataFrame.sort_index(ascending=[True, False])

# belirtilen index column'una gore azalan siralama yapar
bigmacDataFrame.sort_index(level=0, ascending=False)
bigmacDataFrame.sort_index(level='Date', ascending=False)

                          Price in US Dollars
Date       Location
2016-01-01 Vietnam                       2.67
           Venezuela                     0.66
           Uruguay                       3.74
           United States                 4.93
           Ukraine                       1.54
...                                       ...
2010-01-01 Canada                        3.97
           Britain                       3.67
           Brazil                        4.76
           Australia                     3.98
           Argentina                     1.84

[652 rows x 1 columns]

In [16]:
# multi index calisirken index olarak ilk elemani outer index degeri, ikinci elemani inner index degeri olan bir tuple kullaniriz
bigmacDataFrame.loc[('2016-01-01', 'Argentina'), "Price in US Dollars"]
bigmacDataFrame.loc[('2016-01-01', 'Argentina')]

# sadece outer index'i tek ogeli bir tuple olarak gonderebiliriz
bigmacDataFrame.loc[('2016-01-01')].head()
bigmacDataFrame.loc['2016-01-01'].head()

           Price in US Dollars
Location
Argentina                 2.39
Australia                 3.74
Brazil                    3.35
Britain                   4.22
Canada                    4.14

In [61]:
# dataframe'in transpozunu alir
bigmacDataFrameTransposed = bigmacDataFrame.transpose()

# belirttigim satir ve sutundaki deger donduruldu
bigmacDataFrameTransposed.loc[('Price in US Dollars'), ('2010-01-01', 'Australia')]

# index'i belirttigim tuple'da sona virgul ekledigim icin seri donduruldu
bigmacDataFrameTransposed.loc[('Price in US Dollars', ), ('2010-01-01', 'Australia')]

# belirttigim index degeri ve column degerleri araligindaki degerleri getirir
bigmacDataFrameTransposed.loc[('Price in US Dollars',), ('2010-01-01', 'Sweden'):('2010-01-01', 'Turkey')]

Date                2010-01-01
Country                 Sweden Switzerland Taiwan Thailand Turkey
Price in US Dollars       5.51         6.3   2.36     2.11   3.83

In [71]:
temp = bigmacDataFrame.copy()

# iki index column'lu bir multi index yapisi varsa inner index'i outer, outer index'i inner index yapar
# kalici degisiklik yapmaz
temp.swaplevel()

# degistirilecek index column'larini manuel olarak verebiliriz
temp.swaplevel('Country', 'Date').head()

                      Price in US Dollars
Country   Date
Argentina 2010-01-01                 1.84
Australia 2010-01-01                 3.98
Brazil    2010-01-01                 4.76
Britain   2010-01-01                 3.67
Canada    2010-01-01                 3.97

In [75]:
worldDataFrame = pd.read_csv('resources/worldstats.csv', index_col=['country', 'year'])
worldDataFrame.head()

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [80]:
# column adlarini her kayit icin satira indirerek verilerin manipulasyonunu kolaylastirir
worldDataFrame.stack()

# stack islemini geri cevirir
worldDataFrame.unstack()

country     year
Arab World  2015  Population    3.920223e+08
                  GDP           2.530102e+12
            2014  Population    3.842226e+08
                  GDP           2.873600e+12
            2013  Population    3.765043e+08
                                    ...
Zimbabwe    1962  GDP           1.117602e+09
            1961  Population    3.876638e+06
                  GDP           1.096647e+09
            1960  Population    3.752390e+06
                  GDP           1.052990e+09
Length: 22422, dtype: float64

In [88]:
salesmenDataFrame = pd.read_csv('resources/salesmen.csv', parse_dates=['Date'])
salesmenDataFrame.head()

        Date Salesman  Revenue
0 2016-01-01      Bob     7172
1 2016-01-02      Bob     6362
2 2016-01-03      Bob     5982
3 2016-01-04      Bob     7917
4 2016-01-05      Bob     7837

In [89]:
# pivot olusturmak icin tekrar eden degerlerin sikliklarini kontrol ederiz
salesmenDataFrame.value_counts()

Date        Salesman  Revenue
2016-01-01  Bob       7172       1
2016-09-02  Ronald    5299       1
            Jeb       8239       1
            Dave      8638       1
            Bob       7870       1
                                ..
2016-05-01  Dave      9098       1
            Bob       3917       1
2016-04-30  Ronald    7051       1
            Oscar     267        1
2016-12-31  Ronald    2619       1
Length: 1830, dtype: int64

In [92]:
# index olarak verilen column'u index olarak kullanir
# columns olarak verilen column'un unique degerlerini yukarida row olarak gosterir
# values olarak verilen degerleri, Salesman column'u ile Date column degerlerinin kesisimlerine yerlestirir
salesmenDataFrame.pivot(index='Date', columns='Salesman', values='Revenue').head()

Salesman     Bob  Dave   Jeb  Oscar  Ronald
Date
2016-01-01  7172  1864  4430   5250    2639
2016-01-02  6362  8278  8026   8661    4951
2016-01-03  5982  4226  5188   7075    2703
2016-01-04  7917  3868  3144   2524    4258
2016-01-05  7837  2287   938   2793    7771

In [95]:
foodsDataFrame = pd.read_csv('resources/foods.csv')

In [108]:
# cinsiyetlere gore ortalama yapilan odemelerin ortalamasi
result = foodsDataFrame.pivot_table(values='Spend', index='Gender', aggfunc='mean')

# cinsiyetlere gore toplam yapilan odemelerin toplami
result = foodsDataFrame.pivot_table(values='Spend', index='Gender', aggfunc='sum')

# cinsiyetlere gore yapilan en dusuk odeme
result = foodsDataFrame.pivot_table(values='Spend', index='Gender', aggfunc='min')

# cinsiyetlere gore standart sapma belirtir
result = foodsDataFrame.pivot_table(values='Spend', index='Gender', aggfunc='std')

# cinsiyetlere gore yapilan maksimum odemeleri verir
result = foodsDataFrame.pivot_table(values='Spend', index='Gender', aggfunc='max')

# cinsiyetlere gore yapilan odemeleri siraladigimizda ortadaki degeri verir
result = foodsDataFrame.pivot_table(values='Spend', index='Gender', aggfunc='median')

# cinsiyetlere gore yapilan harcamalarin sayisini verir
result = foodsDataFrame.pivot_table(values='Spend', index='Gender', aggfunc='count')

result

        Spend
Gender
Female    512
Male      488

In [111]:
foodsDataFrame.pivot_table(values='Spend', index=['Gender', 'Item'], aggfunc='count')

                  Spend
Gender Item
Female Burger        82
       Burrito       85
       Chalupa       76
       Donut         95
       Ice Cream     81
       Sushi         93
Male   Burger        74
       Burrito       83
       Chalupa       71
       Donut         92
       Ice Cream     95
       Sushi         73

In [113]:
foodsDataFrame.pivot_table(values='Spend', index=['Gender', 'Item'], columns=['Frequency', 'City'], aggfunc='count')
pd.pivot_table(foodsDataFrame, values='Spend', index=['Gender', 'Item'], columns=['Frequency', 'City'], aggfunc='count')

Frequency           Daily                        Monthly               \
City             New York Philadelphia Stamford New York Philadelphia
Gender Item
Female Burger         6.0          3.0      3.0      3.0          4.0
       Burrito        5.0          6.0      5.0      3.0          2.0
       Chalupa        1.0          1.0      1.0      2.0          4.0
       Donut         12.0          4.0      3.0      4.0          1.0
       Ice Cream      4.0          3.0      2.0      2.0          2.0
       Sushi          2.0          6.0      7.0      2.0          1.0
Male   Burger         5.0          3.0      4.0      3.0          3.0
       Burrito        3.0          4.0      4.0      3.0          3.0
       Chalupa        2.0          4.0      4.0      5.0          2.0
       Donut          5.0          4.0      2.0      4.0          5.0
       Ice Cream      3.0          5.0      1.0      3.0          6.0
       Sushi          4.0          6.0      NaN      8.0          2.0

Frequency                    Never                          Often  ...  \
City             Stamford New York Philadelphia Stamford New York  ...
Gender Item                                                        ...
Female Burger         4.0      1.0          4.0      2.0      4.0  ...
       Burrito        1.0      4.0          6.0      7.0      3.0  ...
       Chalupa        2.0      1.0          4.0      3.0      1.0  ...
       Donut          5.0      1.0          6.0      3.0      4.0  ...
       Ice Cream      3.0      3.0          4.0      1.0      4.0  ...
       Sushi          2.0      1.0          4.0      1.0      7.0  ...
Male   Burger         2.0      1.0          2.0      NaN      2.0  ...
       Burrito        3.0      3.0          8.0      5.0      4.0  ...
       Chalupa        6.0      5.0          5.0      3.0      4.0  ...
       Donut          4.0      5.0          2.0      4.0      3.0  ...
       Ice Cream      1.0      2.0          4.0      3.0      5.0  ...
       Sushi          1.0      3.0          6.0      3.0      1.0  ...

Frequency            Once   Seldom                         Weekly  \
City             Stamford New York Philadelphia Stamford New York
Gender Item
Female Burger         3.0      2.0          7.0      2.0      2.0
       Burrito        3.0      2.0          4.0      3.0      3.0
       Chalupa        1.0      4.0          5.0      3.0      4.0
       Donut          2.0      3.0          4.0      3.0      4.0
       Ice Cream      5.0      3.0          4.0      2.0      4.0
       Sushi          5.0      1.0          5.0      1.0      8.0
Male   Burger         9.0      3.0          4.0      3.0      1.0
       Burrito        2.0      3.0          1.0      1.0      4.0
       Chalupa        NaN      1.0          2.0      5.0      3.0
       Donut          5.0      1.0          3.0      4.0      2.0
       Ice Cream      5.0      4.0          2.0      2.0      5.0
       Sushi          5.0      3.0          1.0      3.0      3.0

Frequency                                Yearly
City             Philadelphia Stamford New York Philadelphia Stamford
Gender Item
Female Burger             2.0      5.0      4.0          2.0      6.0
       Burrito            2.0      5.0      2.0          3.0      4.0
       Chalupa            3.0      3.0      3.0          9.0      5.0
       Donut              3.0      8.0      1.0          3.0      4.0
       Ice Cream          6.0      5.0      4.0          4.0      1.0
       Sushi              6.0      6.0      5.0          3.0      8.0
Male   Burger             3.0      4.0      2.0          4.0      5.0
       Burrito            6.0      4.0      4.0          2.0      8.0
       Chalupa            4.0      1.0      3.0          2.0      2.0
       Donut              3.0      5.0      4.0          2.0      1.0
       Ice Cream          4.0      5.0      3.0          5.0      3.0
       Sushi              5.0      4.0      3.0          1.0      1.0

[12 rows x 24 columns]

In [114]:
quartersDataFrame = pd.read_csv('resources/quarters.csv')

In [116]:
# pivot table seklinde yani yatayda uzun halde verilmis olan dataframe'i long yani asagiya dogru uzayacak sekilde duzenler
pd.melt(quartersDataFrame, id_vars=['Salesman']).head()

  Salesman variable   value
0    Boris       Q1  602908
1      Bob       Q1   43790
2    Tommy       Q1  392668
3   Travis       Q1  834663
4   Donald       Q1  580935

In [120]:
# pivot table seklinde yani yatayda uzun halde verilmis olan dataframe'i long yani asagiya dogru uzayacak sekilde duzenler
pd.melt(quartersDataFrame, id_vars=['Salesman'], var_name='Quarter', value_name='Revenue').head()

  Salesman Quarter  Revenue
0    Boris      Q1   602908
1      Bob      Q1    43790
2    Tommy      Q1   392668
3   Travis      Q1   834663
4   Donald      Q1   580935