In [1]:
# pandas kutuphanesini import eder
import pandas as pd

In [2]:
animals = ['cow', 'donkey', 'chicken', 'snake', 'panda']

# bir pandas series olusturur
# varsayilan olarak index'ler sifirdan baslar
pd.Series(animals)

0        cow
1     donkey
2    chicken
3      snake
4      panda
dtype: object

In [3]:
phoneNumbers = {
    'umut yenidil' : '+905555555555',
    'yildiray abdioglu' : '+905554444444',
    'alperen aktug' : '+9055533333333'
}

# index'leri key degerlerinden olusan bir pandas series olusturur
pd.Series(phoneNumbers)

umut yenidil          +905555555555
yildiray abdioglu     +905554444444
alperen aktug        +9055533333333
dtype: object

In [16]:
tempList = [1, 2, 3, 4, 5]

tempSeries = pd.Series(tempList)

In [8]:
# elemanlarin toplamini verir
# series'de aritmetik islem yapamayacagi bir veri turu varsa (ornegin string) hata verir
tempSeries.sum()

15

In [17]:
# elemanlarin carpimini verir
# series'de bir string varsa sonuc olarak bos bir string dondurur
tempSeries.product()

numpy.int64

In [18]:
# ortalamayi verir
tempSeries.mean()

3.0

In [19]:
# standart sapmayi verir
tempSeries.std()

1.5811388300841898

In [20]:
# minimum degeri verir
tempSeries.min()

1

In [21]:
# maksimum degeri verir
tempSeries.max()

5

In [22]:
# series'deki eleman sayisini verir
tempSeries.size

5

In [23]:
# series'de tekrar eden eleman yoksa True, varsa False dondurur
tempSeries.is_unique

True

In [24]:
# series'deki elemanlar ile bir numpy array dondurur
# bu numpy array ile numpy kutuphanesindeki ozellikleri kullanabiliriz
tempSeries.values

array([1, 2, 3, 4, 5], dtype=int64)

In [30]:
# series'in index degerleri integer turunde ise index'leri iceren 
# RangeIndex turunde, 
# degilse yine series turunde bir nesne dondurur
tempSeries.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
# eger series'deki butun elemanlarin turu ayni ise elemanlarin turunu dondurur
# eger farkli turden elemanlar varsa 'object' turunu dondurur
tempSeries.dtype

dtype('int64')

In [34]:
indexes = ['a', 'b', 'c', 'd']
values = [13, 23, 33, 43]

# ilk parametreyi degerler, ikinci parametreyi index'leri olacak sekilde bir series dondurur
pd.Series(values, indexes)

# isimlendirilmis parametre olarak da gonderebiliriz, o zaman hangi sira ile dondurdugumuzun onemi kalmaz
pd.Series(index=indexes, data=values)

a    13
b    23
c    33
d    43
dtype: int64

In [35]:
# belirtilen yoldaki csv dosyasindaki veriler ile bir dataframe olusturur
pokemonDataFrame = pd.read_csv('resources\pokemon.csv')

In [38]:
# usecols parametresi ile ilgili verideki sadece istedigimiz column'lari alabiliriz
tempDataFrame = pd.read_csv('resources\pokemon.csv', usecols=['Pokemon'])

In [39]:
# tek column'u olan dataframe'i bir series'e cevirir
tempDataFrame.squeeze()

# eger dataframe'de birden fazla column varsa sadece ilk column'dan bir series olusturur
tempDataFrame.squeeze('columns')
tempDataFrame.squeeze(axis='columns')

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
716       Yveltal
717       Zygarde
718       Diancie
719         Hoopa
720     Volcanion
Name: Pokemon, Length: 721, dtype: object

In [41]:
# dataframe'in veya series'in bastan ilk 5 elemanini verir varsayilan olarak
pokemonDataFrame.head()

# dataframe'in veya series'in belirtilen sayi kadarini verir bastan
pokemonDataFrame.head(3)
pokemonDataFrame.head(n=3)

     Pokemon   Type
0  Bulbasaur  Grass
1    Ivysaur  Grass
2   Venusaur  Grass

In [42]:
# dataframe'in veya series'in sondan ilk 5 elemanini verir varsayilan olarak
pokemonDataFrame.tail()

# dataframe'in veya series'in belirtilen sayi kadarini verir sondan
pokemonDataFrame.tail(3)
pokemonDataFrame.tail(n=3)

       Pokemon     Type
718    Diancie     Rock
719      Hoopa  Psychic
720  Volcanion     Fire

In [43]:
# dataframe'deki satir sayisini verir
len(pokemonDataFrame)

721

In [46]:
# dataframe'in sirasiyla satir sayisi ve sutun sayisini iceren bir tuple dondurur
pokemonDataFrame.shape

(721, 2)

In [52]:
tempSeries = pokemonDataFrame['Pokemon'].squeeze()

# series'deki elemanlari siralar, yeni bir liste dondurur
sorted(tempSeries)

['Abomasnow',
 'Abra',
 'Absol',
 'Accelgor',
 'Aegislash',
 'Aerodactyl',
 'Aggron',
 'Aipom',
 'Alakazam',
 'Alomomola',
 'Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'Anorith',
 'Arbok',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Ariados',
 'Armaldo',
 'Aromatisse',
 'Aron',
 'Articuno',
 'Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'Barbaracle',
 'Barboach',
 'Basculin',
 'Bastiodon',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blastoise',
 'Blaziken',
 'Blissey',
 'Blitzle',
 'Boldore',
 'Bonsly',
 'Bouffalant',
 'Braixen',
 'Braviary',
 'Breloom',
 'Bronzong',
 'Bronzor',
 'Budew',
 'Buizel',
 'Bulbasaur',
 'Buneary',
 'Bunnelby',
 'Burmy',
 'Butterfree',
 'Cacnea',
 'Cacturne',
 'Camerupt',
 'Carbink',
 'Carnivine',
 'Carracosta',
 'Carvanha',
 'Cascoon',
 'Castform',
 'Caterpie',
 'Celebi',
 'Chandelure',
 'Chansey',
 'Charizard',
 'Charmander',
 'Charmeleon',
 'Chatot',
 'Cherrim',
 'Cherubi',
 'Chesnaught',
 'Chespin',
 'Chikorita',
 'Chimchar',
 'Chimecho',
 'Chinchou',
 'Chingling',
 'Cinccino',
 'Clamperl',
 'Clauncher',
 'Clawitzer',
 'Claydol',
 'Clefable',
 'Clefairy',
 'Cleffa',
 'Cloyster',
 'Cobalion',
 'Cofagrigus',
 'Combee',
 'Combusken',
 'Conkeldurr',
 'Corphish',
 'Corsola',
 'Cottonee',
 'Cradily',
 'Cranidos',
 'Crawdaunt',
 'Cresselia',
 'Croagunk',
 'Crobat',
 'Croconaw',
 'Crustle',
 'Cryogonal',
 'Cubchoo',
 'Cubone',
 'Cyndaquil',
 'Darkrai',
 'Darmanitan',
 'Darumaka',
 'Dedenne',
 'Deerling',
 'Deino',
 'Delcatty',
 'Delibird',
 'Delphox',
 'Deoxys',
 'Dewgong',
 'Dewott',
 'Dialga',
 'Diancie',
 'Diggersby',
 'Diglett',
 'Ditto',
 'Dodrio',
 'Doduo',
 'Donphan',
 'Doublade',
 'Dragalge',
 'Dragonair',
 'Dragonite',
 'Drapion',
 'Dratini',
 'Drifblim',
 'Drifloon',
 'Drilbur',
 'Drowzee',
 'Druddigon',
 'Ducklett',
 'Dugtrio',
 'Dunsparce',
 'Duosion',
 'Durant',
 'Dusclops',
 'Dusknoir',
 'Duskull',
 'Dustox',
 'Dwebble',
 'Eelektrik',
 'Eelektross',
 'Eevee',
 'Ekans',
 'Electabuzz',
 'Electivire',
 'Electrike',
 'Electrode',
 'Elekid',
 'Elgyem',
 'Emboar',
 'Emolga',
 'Empoleon',
 'Entei',
 'Escavalier',
 'Espeon',
 'Espurr',
 'Excadrill',
 'Exeggcute',
 'Exeggutor',
 'Exploud',
 "Farfetch'd",
 'Fearow',
 'Feebas',
 'Fennekin',
 'Feraligatr',
 'Ferroseed',
 'Ferrothorn',
 'Finneon',
 'Flaaffy',
 'Flabébé',
 'Flareon',
 'Fletchinder',
 'Fletchling',
 'Floatzel',
 'Floette',
 'Florges',
 'Flygon',
 'Foongus',
 'Forretress',
 'Fraxure',
 'Frillish',
 'Froakie',
 'Frogadier',
 'Froslass',
 'Furfrou',
 'Furret',
 'Gabite',
 'Gallade',
 'Galvantula',
 'Garbodor',
 'Garchomp',
 'Gardevoir',
 'Gastly',
 'Gastrodon',
 'Genesect',
 'Gengar',
 'Geodude',
 'Gible',
 'Gigalith',
 'Girafarig',
 'Giratina',
 'Glaceon',
 'Glalie',
 'Glameow',
 'Gligar',
 'Gliscor',
 'Gloom',
 'Gogoat',
 'Golbat',
 'Goldeen',
 'Golduck',
 'Golem',
 'Golett',
 'Golurk',
 'Goodra',
 'Goomy',
 'Gorebyss',
 'Gothita',
 'Gothitelle',
 'Gothorita',
 'Gourgeist',
 'Granbull',
 'Graveler',
 'Greninja',
 'Grimer',
 'Grotle',
 'Groudon',
 'Grovyle',
 'Growlithe',
 'Grumpig',
 'Gulpin',
 'Gurdurr',
 'Gyarados',
 'Happiny',
 'Hariyama',
 'Haunter',
 'Hawlucha',
 'Haxorus',
 'Heatmor',
 'Heatran',
 'Heliolisk',
 'Helioptile',
 'Heracross',
 'Herdier',
 'Hippopotas',
 'Hippowdon',
 'Hitmonchan',
 'Hitmonlee',
 'Hitmontop',
 'Ho-oh',
 'Honchkrow',
 'Honedge',
 'Hoopa',
 'Hoothoot',
 'Hoppip',
 'Horsea',
 'Houndoom',
 'Houndour',
 'Huntail',
 'Hydreigon',
 'Hypno',
 'Igglybuff',
 'Illumise',
 'Infernape',
 'Inkay',
 'Ivysaur',
 'Jellicent',
 'Jigglypuff',
 'Jirachi',
 'Jolteon',
 'Joltik',
 'Jumpluff',
 'Jynx',
 'Kabuto',
 'Kabutops',
 'Kadabra',
 'Kakuna',
 'Kangaskhan',
 'Karrablast',
 'Kecleon',
 'Keldeo',
 'Kingdra',
 'Kingler',
 'Kirlia',
 'Klang',
 'Klefki',
 'Klink',
 'Klinklang',
 'Koffing',
 'Krabby',
 'Kricketot',
 'Kricketune',
 'Krokorok',
 'Krookodile',
 'Kyogre',
 'Kyurem',
 'Lairon',
 'Lampent',
 'Landorus',
 'Lanturn',
 'Lapras',
 'Larvesta',
 'Larvitar',
 'Latias',
 'Latios',
 'Leafeon',
 'Leavanny',
 'Ledian',
 'Ledyba',
 'Lickilicky',
 'Lickitung',
 'Liepard',
 'Lileep',
 'Lilligant',
 'Lillipup',
 'Linoone',
 'Litleo',
 'Litwick',
 'Lombre',
 'Lopunny',
 'Lotad',
 'Loudred',
 'Lucario',
 'Ludicolo',
 'Lugia',
 'Lumineon',
 'Lunatone',
 'Luvdisc',
 'Luxio',
 'Luxray',
 'Machamp',
 'Machoke',
 'Machop',
 'Magby',
 'Magcargo',
 'Magikarp',
 'Magmar',
 'Magmortar',
 'Magnemite',
 'Magneton',
 'Magnezone',
 'Makuhita',
 'Malamar',
 'Mamoswine',
 'Manaphy',
 'Mandibuzz',
 'Manectric',
 'Mankey',
 'Mantine',
 'Mantyke',
 'Maractus',
 'Mareep',
 'Marill',
 'Marowak',
 'Marshtomp',
 'Masquerain',
 'Mawile',
 'Medicham',
 'Meditite',
 'Meganium',
 'Meloetta',
 'Meowstic',
 'Meowth',
 'Mesprit',
 'Metagross',
 'Metang',
 'Metapod',
 'Mew',
 'Mewtwo',
 'Mienfoo',
 'Mienshao',
 'Mightyena',
 'Milotic',
 'Miltank',
 'Mime Jr.',
 'Minccino',
 'Minun',
 'Misdreavus',
 'Mismagius',
 'Moltres',
 'Monferno',
 'Mothim',
 'Mr. Mime',
 'Mudkip',
 'Muk',
 'Munchlax',
 'Munna',
 'Murkrow',
 'Musharna',
 'Natu',
 'Nidoking',
 'Nidoqueen',
 'Nidoran',
 'Nidoran♂',
 'Nidorina',
 'Nidorino',
 'Nincada',
 'Ninetales',
 'Ninjask',
 'Noctowl',
 'Noibat',
 'Noivern',
 'Nosepass',
 'Numel',
 'Nuzleaf',
 'Octillery',
 'Oddish',
 'Omanyte',
 'Omastar',
 'Onix',
 'Oshawott',
 'Pachirisu',
 'Palkia',
 'Palpitoad',
 'Pancham',
 'Pangoro',
 'Panpour',
 'Pansage',
 'Pansear',
 'Paras',
 'Parasect',
 'Patrat',
 'Pawniard',
 'Pelipper',
 'Persian',
 'Petilil',
 'Phanpy',
 'Phantump',
 'Phione',
 'Pichu',
 'Pidgeot',
 'Pidgeotto',
 'Pidgey',
 'Pidove',
 'Pignite',
 'Pikachu',
 'Piloswine',
 'Pineco',
 'Pinsir',
 'Piplup',
 'Plusle',
 'Politoed',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Ponyta',
 'Poochyena',
 'Porygon',
 'Porygon-Z',
 'Porygon2',
 'Primeape',
 'Prinplup',
 'Probopass',
 'Psyduck',
 'Pumpkaboo',
 'Pupitar',
 'Purrloin',
 'Purugly',
 'Pyroar',
 'Quagsire',
 'Quilava',
 'Quilladin',
 'Qwilfish',
 'Raichu',
 'Raikou',
 'Ralts',
 'Rampardos',
 'Rapidash',
 'Raticate',
 'Rattata',
 'Rayquaza',
 'Regice',
 'Regigigas',
 'Regirock',
 'Registeel',
 'Relicanth',
 'Remoraid',
 'Reshiram',
 'Reuniclus',
 'Rhydon',
 'Rhyhorn',
 'Rhyperior',
 'Riolu',
 'Roggenrola',
 'Roselia',
 'Roserade',
 'Rotom',
 'Rufflet',
 'Sableye',
 'Salamence',
 'Samurott',
 'Sandile',
 'Sandshrew',
 'Sandslash',
 'Sawk',
 'Sawsbuck',
 'Scatterbug',
 'Sceptile',
 'Scizor',
 'Scolipede',
 'Scrafty',
 'Scraggy',
 'Scyther',
 'Seadra',
 'Seaking',
 'Sealeo',
 'Seedot',
 'Seel',
 'Seismitoad',
 'Sentret',
 'Serperior',
 'Servine',
 'Seviper',
 'Sewaddle',
 'Sharpedo',
 'Shaymin',
 'Shedinja',
 'Shelgon',
 'Shellder',
 'Shellos',
 'Shelmet',
 'Shieldon',
 'Shiftry',
 'Shinx',
 'Shroomish',
 'Shuckle',
 'Shuppet',
 'Sigilyph',
 'Silcoon',
 'Simipour',
 'Simisage',
 'Simisear',
 'Skarmory',
 'Skiddo',
 'Skiploom',
 'Skitty',
 'Skorupi',
 'Skrelp',
 'Skuntank',
 'Slaking',
 'Slakoth',
 'Sliggoo',
 'Slowbro',
 'Slowking',
 'Slowpoke',
 'Slugma',
 'Slurpuff',
 'Smeargle',
 'Smoochum',
 'Sneasel',
 'Snivy',
 'Snorlax',
 'Snorunt',
 'Snover',
 'Snubbull',
 'Solosis',
 'Solrock',
 'Spearow',
 'Spewpa',
 'Spheal',
 'Spinarak',
 'Spinda',
 'Spiritomb',
 'Spoink',
 'Spritzee',
 'Squirtle',
 'Stantler',
 'Staraptor',
 'Staravia',
 'Starly',
 'Starmie',
 'Staryu',
 'Steelix',
 'Stoutland',
 'Stunfisk',
 'Stunky',
 'Sudowoodo',
 'Suicune',
 'Sunflora',
 'Sunkern',
 'Surskit',
 'Swablu',
 'Swadloon',
 'Swalot',
 'Swampert',
 'Swanna',
 'Swellow',
 'Swinub',
 'Swirlix',
 'Swoobat',
 'Sylveon',
 'Taillow',
 'Talonflame',
 'Tangela',
 'Tangrowth',
 'Tauros',
 'Teddiursa',
 'Tentacool',
 'Tentacruel',
 'Tepig',
 'Terrakion',
 'Throh',
 'Thundurus',
 'Timburr',
 'Tirtouga',
 'Togekiss',
 'Togepi',
 'Togetic',
 'Torchic',
 'Torkoal',
 'Tornadus',
 'Torterra',
 'Totodile',
 'Toxicroak',
 'Tranquill',
 'Trapinch',
 'Treecko',
 'Trevenant',
 'Tropius',
 'Trubbish',
 'Turtwig',
 'Tympole',
 'Tynamo',
 'Typhlosion',
 'Tyranitar',
 'Tyrantrum',
 'Tyrogue',
 'Tyrunt',
 'Umbreon',
 'Unfezant',
 'Unown',
 'Ursaring',
 'Uxie',
 'Vanillish',
 'Vanillite',
 'Vanilluxe',
 'Vaporeon',
 'Venipede',
 'Venomoth',
 'Venonat',
 'Venusaur',
 'Vespiquen',
 'Vibrava',
 'Victini',
 'Victreebel',
 'Vigoroth',
 'Vileplume',
 'Virizion',
 'Vivillon',
 'Volbeat',
 'Volcanion',
 'Volcarona',
 'Voltorb',
 'Vullaby',
 'Vulpix',
 'Wailmer',
 'Wailord',
 'Walrein',
 'Wartortle',
 'Watchog',
 'Weavile',
 'Weedle',
 'Weepinbell',
 'Weezing',
 'Whimsicott',
 'Whirlipede',
 'Whiscash',
 'Whismur',
 'Wigglytuff',
 'Wingull',
 'Wobbuffet',
 'Woobat',
 'Wooper',
 'Wormadam',
 'Wurmple',
 'Wynaut',
 'Xatu',
 'Xerneas',
 'Yamask',
 'Yanma',
 'Yanmega',
 'Yveltal',
 'Zangoose',
 'Zapdos',
 'Zebstrika',
 'Zekrom',
 'Zigzagoon',
 'Zoroark',
 'Zorua',
 'Zubat',
 'Zweilous',
 'Zygarde']

In [53]:
# series'deki elemanlari tersten siralar, liste dondurur
sorted(tempSeries, reverse=True)

['Zygarde',
 'Zweilous',
 'Zubat',
 'Zorua',
 'Zoroark',
 'Zigzagoon',
 'Zekrom',
 'Zebstrika',
 'Zapdos',
 'Zangoose',
 'Yveltal',
 'Yanmega',
 'Yanma',
 'Yamask',
 'Xerneas',
 'Xatu',
 'Wynaut',
 'Wurmple',
 'Wormadam',
 'Wooper',
 'Woobat',
 'Wobbuffet',
 'Wingull',
 'Wigglytuff',
 'Whismur',
 'Whiscash',
 'Whirlipede',
 'Whimsicott',
 'Weezing',
 'Weepinbell',
 'Weedle',
 'Weavile',
 'Watchog',
 'Wartortle',
 'Walrein',
 'Wailord',
 'Wailmer',
 'Vulpix',
 'Vullaby',
 'Voltorb',
 'Volcarona',
 'Volcanion',
 'Volbeat',
 'Vivillon',
 'Virizion',
 'Vileplume',
 'Vigoroth',
 'Victreebel',
 'Victini',
 'Vibrava',
 'Vespiquen',
 'Venusaur',
 'Venonat',
 'Venomoth',
 'Venipede',
 'Vaporeon',
 'Vanilluxe',
 'Vanillite',
 'Vanillish',
 'Uxie',
 'Ursaring',
 'Unown',
 'Unfezant',
 'Umbreon',
 'Tyrunt',
 'Tyrogue',
 'Tyrantrum',
 'Tyranitar',
 'Typhlosion',
 'Tynamo',
 'Tympole',
 'Turtwig',
 'Trubbish',
 'Tropius',
 'Trevenant',
 'Treecko',
 'Trapinch',
 'Tranquill',
 'Toxicroak',
 'Totodile',
 'Torterra',
 'Tornadus',
 'Torkoal',
 'Torchic',
 'Togetic',
 'Togepi',
 'Togekiss',
 'Tirtouga',
 'Timburr',
 'Thundurus',
 'Throh',
 'Terrakion',
 'Tepig',
 'Tentacruel',
 'Tentacool',
 'Teddiursa',
 'Tauros',
 'Tangrowth',
 'Tangela',
 'Talonflame',
 'Taillow',
 'Sylveon',
 'Swoobat',
 'Swirlix',
 'Swinub',
 'Swellow',
 'Swanna',
 'Swampert',
 'Swalot',
 'Swadloon',
 'Swablu',
 'Surskit',
 'Sunkern',
 'Sunflora',
 'Suicune',
 'Sudowoodo',
 'Stunky',
 'Stunfisk',
 'Stoutland',
 'Steelix',
 'Staryu',
 'Starmie',
 'Starly',
 'Staravia',
 'Staraptor',
 'Stantler',
 'Squirtle',
 'Spritzee',
 'Spoink',
 'Spiritomb',
 'Spinda',
 'Spinarak',
 'Spheal',
 'Spewpa',
 'Spearow',
 'Solrock',
 'Solosis',
 'Snubbull',
 'Snover',
 'Snorunt',
 'Snorlax',
 'Snivy',
 'Sneasel',
 'Smoochum',
 'Smeargle',
 'Slurpuff',
 'Slugma',
 'Slowpoke',
 'Slowking',
 'Slowbro',
 'Sliggoo',
 'Slakoth',
 'Slaking',
 'Skuntank',
 'Skrelp',
 'Skorupi',
 'Skitty',
 'Skiploom',
 'Skiddo',
 'Skarmory',
 'Simisear',
 'Simisage',
 'Simipour',
 'Silcoon',
 'Sigilyph',
 'Shuppet',
 'Shuckle',
 'Shroomish',
 'Shinx',
 'Shiftry',
 'Shieldon',
 'Shelmet',
 'Shellos',
 'Shellder',
 'Shelgon',
 'Shedinja',
 'Shaymin',
 'Sharpedo',
 'Sewaddle',
 'Seviper',
 'Servine',
 'Serperior',
 'Sentret',
 'Seismitoad',
 'Seel',
 'Seedot',
 'Sealeo',
 'Seaking',
 'Seadra',
 'Scyther',
 'Scraggy',
 'Scrafty',
 'Scolipede',
 'Scizor',
 'Sceptile',
 'Scatterbug',
 'Sawsbuck',
 'Sawk',
 'Sandslash',
 'Sandshrew',
 'Sandile',
 'Samurott',
 'Salamence',
 'Sableye',
 'Rufflet',
 'Rotom',
 'Roserade',
 'Roselia',
 'Roggenrola',
 'Riolu',
 'Rhyperior',
 'Rhyhorn',
 'Rhydon',
 'Reuniclus',
 'Reshiram',
 'Remoraid',
 'Relicanth',
 'Registeel',
 'Regirock',
 'Regigigas',
 'Regice',
 'Rayquaza',
 'Rattata',
 'Raticate',
 'Rapidash',
 'Rampardos',
 'Ralts',
 'Raikou',
 'Raichu',
 'Qwilfish',
 'Quilladin',
 'Quilava',
 'Quagsire',
 'Pyroar',
 'Purugly',
 'Purrloin',
 'Pupitar',
 'Pumpkaboo',
 'Psyduck',
 'Probopass',
 'Prinplup',
 'Primeape',
 'Porygon2',
 'Porygon-Z',
 'Porygon',
 'Poochyena',
 'Ponyta',
 'Poliwrath',
 'Poliwhirl',
 'Poliwag',
 'Politoed',
 'Plusle',
 'Piplup',
 'Pinsir',
 'Pineco',
 'Piloswine',
 'Pikachu',
 'Pignite',
 'Pidove',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Pichu',
 'Phione',
 'Phantump',
 'Phanpy',
 'Petilil',
 'Persian',
 'Pelipper',
 'Pawniard',
 'Patrat',
 'Parasect',
 'Paras',
 'Pansear',
 'Pansage',
 'Panpour',
 'Pangoro',
 'Pancham',
 'Palpitoad',
 'Palkia',
 'Pachirisu',
 'Oshawott',
 'Onix',
 'Omastar',
 'Omanyte',
 'Oddish',
 'Octillery',
 'Nuzleaf',
 'Numel',
 'Nosepass',
 'Noivern',
 'Noibat',
 'Noctowl',
 'Ninjask',
 'Ninetales',
 'Nincada',
 'Nidorino',
 'Nidorina',
 'Nidoran♂',
 'Nidoran',
 'Nidoqueen',
 'Nidoking',
 'Natu',
 'Musharna',
 'Murkrow',
 'Munna',
 'Munchlax',
 'Muk',
 'Mudkip',
 'Mr. Mime',
 'Mothim',
 'Monferno',
 'Moltres',
 'Mismagius',
 'Misdreavus',
 'Minun',
 'Minccino',
 'Mime Jr.',
 'Miltank',
 'Milotic',
 'Mightyena',
 'Mienshao',
 'Mienfoo',
 'Mewtwo',
 'Mew',
 'Metapod',
 'Metang',
 'Metagross',
 'Mesprit',
 'Meowth',
 'Meowstic',
 'Meloetta',
 'Meganium',
 'Meditite',
 'Medicham',
 'Mawile',
 'Masquerain',
 'Marshtomp',
 'Marowak',
 'Marill',
 'Mareep',
 'Maractus',
 'Mantyke',
 'Mantine',
 'Mankey',
 'Manectric',
 'Mandibuzz',
 'Manaphy',
 'Mamoswine',
 'Malamar',
 'Makuhita',
 'Magnezone',
 'Magneton',
 'Magnemite',
 'Magmortar',
 'Magmar',
 'Magikarp',
 'Magcargo',
 'Magby',
 'Machop',
 'Machoke',
 'Machamp',
 'Luxray',
 'Luxio',
 'Luvdisc',
 'Lunatone',
 'Lumineon',
 'Lugia',
 'Ludicolo',
 'Lucario',
 'Loudred',
 'Lotad',
 'Lopunny',
 'Lombre',
 'Litwick',
 'Litleo',
 'Linoone',
 'Lillipup',
 'Lilligant',
 'Lileep',
 'Liepard',
 'Lickitung',
 'Lickilicky',
 'Ledyba',
 'Ledian',
 'Leavanny',
 'Leafeon',
 'Latios',
 'Latias',
 'Larvitar',
 'Larvesta',
 'Lapras',
 'Lanturn',
 'Landorus',
 'Lampent',
 'Lairon',
 'Kyurem',
 'Kyogre',
 'Krookodile',
 'Krokorok',
 'Kricketune',
 'Kricketot',
 'Krabby',
 'Koffing',
 'Klinklang',
 'Klink',
 'Klefki',
 'Klang',
 'Kirlia',
 'Kingler',
 'Kingdra',
 'Keldeo',
 'Kecleon',
 'Karrablast',
 'Kangaskhan',
 'Kakuna',
 'Kadabra',
 'Kabutops',
 'Kabuto',
 'Jynx',
 'Jumpluff',
 'Joltik',
 'Jolteon',
 'Jirachi',
 'Jigglypuff',
 'Jellicent',
 'Ivysaur',
 'Inkay',
 'Infernape',
 'Illumise',
 'Igglybuff',
 'Hypno',
 'Hydreigon',
 'Huntail',
 'Houndour',
 'Houndoom',
 'Horsea',
 'Hoppip',
 'Hoothoot',
 'Hoopa',
 'Honedge',
 'Honchkrow',
 'Ho-oh',
 'Hitmontop',
 'Hitmonlee',
 'Hitmonchan',
 'Hippowdon',
 'Hippopotas',
 'Herdier',
 'Heracross',
 'Helioptile',
 'Heliolisk',
 'Heatran',
 'Heatmor',
 'Haxorus',
 'Hawlucha',
 'Haunter',
 'Hariyama',
 'Happiny',
 'Gyarados',
 'Gurdurr',
 'Gulpin',
 'Grumpig',
 'Growlithe',
 'Grovyle',
 'Groudon',
 'Grotle',
 'Grimer',
 'Greninja',
 'Graveler',
 'Granbull',
 'Gourgeist',
 'Gothorita',
 'Gothitelle',
 'Gothita',
 'Gorebyss',
 'Goomy',
 'Goodra',
 'Golurk',
 'Golett',
 'Golem',
 'Golduck',
 'Goldeen',
 'Golbat',
 'Gogoat',
 'Gloom',
 'Gliscor',
 'Gligar',
 'Glameow',
 'Glalie',
 'Glaceon',
 'Giratina',
 'Girafarig',
 'Gigalith',
 'Gible',
 'Geodude',
 'Gengar',
 'Genesect',
 'Gastrodon',
 'Gastly',
 'Gardevoir',
 'Garchomp',
 'Garbodor',
 'Galvantula',
 'Gallade',
 'Gabite',
 'Furret',
 'Furfrou',
 'Froslass',
 'Frogadier',
 'Froakie',
 'Frillish',
 'Fraxure',
 'Forretress',
 'Foongus',
 'Flygon',
 'Florges',
 'Floette',
 'Floatzel',
 'Fletchling',
 'Fletchinder',
 'Flareon',
 'Flabébé',
 'Flaaffy',
 'Finneon',
 'Ferrothorn',
 'Ferroseed',
 'Feraligatr',
 'Fennekin',
 'Feebas',
 'Fearow',
 "Farfetch'd",
 'Exploud',
 'Exeggutor',
 'Exeggcute',
 'Excadrill',
 'Espurr',
 'Espeon',
 'Escavalier',
 'Entei',
 'Empoleon',
 'Emolga',
 'Emboar',
 'Elgyem',
 'Elekid',
 'Electrode',
 'Electrike',
 'Electivire',
 'Electabuzz',
 'Ekans',
 'Eevee',
 'Eelektross',
 'Eelektrik',
 'Dwebble',
 'Dustox',
 'Duskull',
 'Dusknoir',
 'Dusclops',
 'Durant',
 'Duosion',
 'Dunsparce',
 'Dugtrio',
 'Ducklett',
 'Druddigon',
 'Drowzee',
 'Drilbur',
 'Drifloon',
 'Drifblim',
 'Dratini',
 'Drapion',
 'Dragonite',
 'Dragonair',
 'Dragalge',
 'Doublade',
 'Donphan',
 'Doduo',
 'Dodrio',
 'Ditto',
 'Diglett',
 'Diggersby',
 'Diancie',
 'Dialga',
 'Dewott',
 'Dewgong',
 'Deoxys',
 'Delphox',
 'Delibird',
 'Delcatty',
 'Deino',
 'Deerling',
 'Dedenne',
 'Darumaka',
 'Darmanitan',
 'Darkrai',
 'Cyndaquil',
 'Cubone',
 'Cubchoo',
 'Cryogonal',
 'Crustle',
 'Croconaw',
 'Crobat',
 'Croagunk',
 'Cresselia',
 'Crawdaunt',
 'Cranidos',
 'Cradily',
 'Cottonee',
 'Corsola',
 'Corphish',
 'Conkeldurr',
 'Combusken',
 'Combee',
 'Cofagrigus',
 'Cobalion',
 'Cloyster',
 'Cleffa',
 'Clefairy',
 'Clefable',
 'Claydol',
 'Clawitzer',
 'Clauncher',
 'Clamperl',
 'Cinccino',
 'Chingling',
 'Chinchou',
 'Chimecho',
 'Chimchar',
 'Chikorita',
 'Chespin',
 'Chesnaught',
 'Cherubi',
 'Cherrim',
 'Chatot',
 'Charmeleon',
 'Charmander',
 'Charizard',
 'Chansey',
 'Chandelure',
 'Celebi',
 'Caterpie',
 'Castform',
 'Cascoon',
 'Carvanha',
 'Carracosta',
 'Carnivine',
 'Carbink',
 'Camerupt',
 'Cacturne',
 'Cacnea',
 'Butterfree',
 'Burmy',
 'Bunnelby',
 'Buneary',
 'Bulbasaur',
 'Buizel',
 'Budew',
 'Bronzor',
 'Bronzong',
 'Breloom',
 'Braviary',
 'Braixen',
 'Bouffalant',
 'Bonsly',
 'Boldore',
 'Blitzle',
 'Blissey',
 'Blaziken',
 'Blastoise',
 'Bisharp',
 'Binacle',
 'Bidoof',
 'Bibarel',
 'Bergmite',
 'Bellsprout',
 'Bellossom',
 'Beldum',
 'Beheeyem',
 'Beedrill',
 'Beautifly',
 'Beartic',
 'Bayleef',
 'Bastiodon',
 'Basculin',
 'Barboach',
 'Barbaracle',
 'Banette',
 'Baltoy',
 'Bagon',
 'Azurill',
 'Azumarill',
 'Azelf',
 'Axew',
 'Avalugg',
 'Aurorus',
 'Audino',
 'Articuno',
 'Aron',
 'Aromatisse',
 'Armaldo',
 'Ariados',
 'Archeops',
 'Archen',
 'Arceus',
 'Arcanine',
 'Arbok',
 'Anorith',
 'Ampharos',
 'Amoonguss',
 'Ambipom',
 'Amaura',
 'Altaria',
 'Alomomola',
 'Alakazam',
 'Aipom',
 'Aggron',
 'Aerodactyl',
 'Aegislash',
 'Accelgor',
 'Absol',
 'Abra',
 'Abomasnow']

In [54]:
# verilen series'i listeye donusturur
list(tempSeries)

['Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 "Farfetch'd",
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew',
 'Chikorita',
 'Bayleef',
 'Meganium',
 'Cyndaquil',
 'Quilava',
 'Typhlosion',
 'Totodile',
 'Croconaw',
 'Feraligatr',
 'Sentret',
 'Furret',
 'Hoothoot',
 'Noctowl',
 'Ledyba',
 'Ledian',
 'Spinarak',
 'Ariados',
 'Crobat',
 'Chinchou',
 'Lanturn',
 'Pichu',
 'Cleffa',
 'Igglybuff',
 'Togepi',
 'Togetic',
 'Natu',
 'Xatu',
 'Mareep',
 'Flaaffy',
 'Ampharos',
 'Bellossom',
 'Marill',
 'Azumarill',
 'Sudowoodo',
 'Politoed',
 'Hoppip',
 'Skiploom',
 'Jumpluff',
 'Aipom',
 'Sunkern',
 'Sunflora',
 'Yanma',
 'Wooper',
 'Quagsire',
 'Espeon',
 'Umbreon',
 'Murkrow',
 'Slowking',
 'Misdreavus',
 'Unown',
 'Wobbuffet',
 'Girafarig',
 'Pineco',
 'Forretress',
 'Dunsparce',
 'Gligar',
 'Steelix',
 'Snubbull',
 'Granbull',
 'Qwilfish',
 'Scizor',
 'Shuckle',
 'Heracross',
 'Sneasel',
 'Teddiursa',
 'Ursaring',
 'Slugma',
 'Magcargo',
 'Swinub',
 'Piloswine',
 'Corsola',
 'Remoraid',
 'Octillery',
 'Delibird',
 'Mantine',
 'Skarmory',
 'Houndour',
 'Houndoom',
 'Kingdra',
 'Phanpy',
 'Donphan',
 'Porygon2',
 'Stantler',
 'Smeargle',
 'Tyrogue',
 'Hitmontop',
 'Smoochum',
 'Elekid',
 'Magby',
 'Miltank',
 'Blissey',
 'Raikou',
 'Entei',
 'Suicune',
 'Larvitar',
 'Pupitar',
 'Tyranitar',
 'Lugia',
 'Ho-oh',
 'Celebi',
 'Treecko',
 'Grovyle',
 'Sceptile',
 'Torchic',
 'Combusken',
 'Blaziken',
 'Mudkip',
 'Marshtomp',
 'Swampert',
 'Poochyena',
 'Mightyena',
 'Zigzagoon',
 'Linoone',
 'Wurmple',
 'Silcoon',
 'Beautifly',
 'Cascoon',
 'Dustox',
 'Lotad',
 'Lombre',
 'Ludicolo',
 'Seedot',
 'Nuzleaf',
 'Shiftry',
 'Taillow',
 'Swellow',
 'Wingull',
 'Pelipper',
 'Ralts',
 'Kirlia',
 'Gardevoir',
 'Surskit',
 'Masquerain',
 'Shroomish',
 'Breloom',
 'Slakoth',
 'Vigoroth',
 'Slaking',
 'Nincada',
 'Ninjask',
 'Shedinja',
 'Whismur',
 'Loudred',
 'Exploud',
 'Makuhita',
 'Hariyama',
 'Azurill',
 'Nosepass',
 'Skitty',
 'Delcatty',
 'Sableye',
 'Mawile',
 'Aron',
 'Lairon',
 'Aggron',
 'Meditite',
 'Medicham',
 'Electrike',
 'Manectric',
 'Plusle',
 'Minun',
 'Volbeat',
 'Illumise',
 'Roselia',
 'Gulpin',
 'Swalot',
 'Carvanha',
 'Sharpedo',
 'Wailmer',
 'Wailord',
 'Numel',
 'Camerupt',
 'Torkoal',
 'Spoink',
 'Grumpig',
 'Spinda',
 'Trapinch',
 'Vibrava',
 'Flygon',
 'Cacnea',
 'Cacturne',
 'Swablu',
 'Altaria',
 'Zangoose',
 'Seviper',
 'Lunatone',
 'Solrock',
 'Barboach',
 'Whiscash',
 'Corphish',
 'Crawdaunt',
 'Baltoy',
 'Claydol',
 'Lileep',
 'Cradily',
 'Anorith',
 'Armaldo',
 'Feebas',
 'Milotic',
 'Castform',
 'Kecleon',
 'Shuppet',
 'Banette',
 'Duskull',
 'Dusclops',
 'Tropius',
 'Chimecho',
 'Absol',
 'Wynaut',
 'Snorunt',
 'Glalie',
 'Spheal',
 'Sealeo',
 'Walrein',
 'Clamperl',
 'Huntail',
 'Gorebyss',
 'Relicanth',
 'Luvdisc',
 'Bagon',
 'Shelgon',
 'Salamence',
 'Beldum',
 'Metang',
 'Metagross',
 'Regirock',
 'Regice',
 'Registeel',
 'Latias',
 'Latios',
 'Kyogre',
 'Groudon',
 'Rayquaza',
 'Jirachi',
 'Deoxys',
 'Turtwig',
 'Grotle',
 'Torterra',
 'Chimchar',
 'Monferno',
 'Infernape',
 'Piplup',
 'Prinplup',
 'Empoleon',
 'Starly',
 'Staravia',
 'Staraptor',
 'Bidoof',
 'Bibarel',
 'Kricketot',
 'Kricketune',
 'Shinx',
 'Luxio',
 'Luxray',
 'Budew',
 'Roserade',
 'Cranidos',
 'Rampardos',
 'Shieldon',
 'Bastiodon',
 'Burmy',
 'Wormadam',
 'Mothim',
 'Combee',
 'Vespiquen',
 'Pachirisu',
 'Buizel',
 'Floatzel',
 'Cherubi',
 'Cherrim',
 'Shellos',
 'Gastrodon',
 'Ambipom',
 'Drifloon',
 'Drifblim',
 'Buneary',
 'Lopunny',
 'Mismagius',
 'Honchkrow',
 'Glameow',
 'Purugly',
 'Chingling',
 'Stunky',
 'Skuntank',
 'Bronzor',
 'Bronzong',
 'Bonsly',
 'Mime Jr.',
 'Happiny',
 'Chatot',
 'Spiritomb',
 'Gible',
 'Gabite',
 'Garchomp',
 'Munchlax',
 'Riolu',
 'Lucario',
 'Hippopotas',
 'Hippowdon',
 'Skorupi',
 'Drapion',
 'Croagunk',
 'Toxicroak',
 'Carnivine',
 'Finneon',
 'Lumineon',
 'Mantyke',
 'Snover',
 'Abomasnow',
 'Weavile',
 'Magnezone',
 'Lickilicky',
 'Rhyperior',
 'Tangrowth',
 'Electivire',
 'Magmortar',
 'Togekiss',
 'Yanmega',
 'Leafeon',
 'Glaceon',
 'Gliscor',
 'Mamoswine',
 'Porygon-Z',
 'Gallade',
 'Probopass',
 'Dusknoir',
 'Froslass',
 'Rotom',
 'Uxie',
 'Mesprit',
 'Azelf',
 'Dialga',
 'Palkia',
 'Heatran',
 'Regigigas',
 'Giratina',
 'Cresselia',
 'Phione',
 'Manaphy',
 'Darkrai',
 'Shaymin',
 'Arceus',
 'Victini',
 'Snivy',
 'Servine',
 'Serperior',
 'Tepig',
 'Pignite',
 'Emboar',
 'Oshawott',
 'Dewott',
 'Samurott',
 'Patrat',
 'Watchog',
 'Lillipup',
 'Herdier',
 'Stoutland',
 'Purrloin',
 'Liepard',
 'Pansage',
 'Simisage',
 'Pansear',
 'Simisear',
 'Panpour',
 'Simipour',
 'Munna',
 'Musharna',
 'Pidove',
 'Tranquill',
 'Unfezant',
 'Blitzle',
 'Zebstrika',
 'Roggenrola',
 'Boldore',
 'Gigalith',
 'Woobat',
 'Swoobat',
 'Drilbur',
 'Excadrill',
 'Audino',
 'Timburr',
 'Gurdurr',
 'Conkeldurr',
 'Tympole',
 'Palpitoad',
 'Seismitoad',
 'Throh',
 'Sawk',
 'Sewaddle',
 'Swadloon',
 'Leavanny',
 'Venipede',
 'Whirlipede',
 'Scolipede',
 'Cottonee',
 'Whimsicott',
 'Petilil',
 'Lilligant',
 'Basculin',
 'Sandile',
 'Krokorok',
 'Krookodile',
 'Darumaka',
 'Darmanitan',
 'Maractus',
 'Dwebble',
 'Crustle',
 'Scraggy',
 'Scrafty',
 'Sigilyph',
 'Yamask',
 'Cofagrigus',
 'Tirtouga',
 'Carracosta',
 'Archen',
 'Archeops',
 'Trubbish',
 'Garbodor',
 'Zorua',
 'Zoroark',
 'Minccino',
 'Cinccino',
 'Gothita',
 'Gothorita',
 'Gothitelle',
 'Solosis',
 'Duosion',
 'Reuniclus',
 'Ducklett',
 'Swanna',
 'Vanillite',
 'Vanillish',
 'Vanilluxe',
 'Deerling',
 'Sawsbuck',
 'Emolga',
 'Karrablast',
 'Escavalier',
 'Foongus',
 'Amoonguss',
 'Frillish',
 'Jellicent',
 'Alomomola',
 'Joltik',
 'Galvantula',
 'Ferroseed',
 'Ferrothorn',
 'Klink',
 'Klang',
 'Klinklang',
 'Tynamo',
 'Eelektrik',
 'Eelektross',
 'Elgyem',
 'Beheeyem',
 'Litwick',
 'Lampent',
 'Chandelure',
 'Axew',
 'Fraxure',
 'Haxorus',
 'Cubchoo',
 'Beartic',
 'Cryogonal',
 'Shelmet',
 'Accelgor',
 'Stunfisk',
 'Mienfoo',
 'Mienshao',
 'Druddigon',
 'Golett',
 'Golurk',
 'Pawniard',
 'Bisharp',
 'Bouffalant',
 'Rufflet',
 'Braviary',
 'Vullaby',
 'Mandibuzz',
 'Heatmor',
 'Durant',
 'Deino',
 'Zweilous',
 'Hydreigon',
 'Larvesta',
 'Volcarona',
 'Cobalion',
 'Terrakion',
 'Virizion',
 'Tornadus',
 'Thundurus',
 'Reshiram',
 'Zekrom',
 'Landorus',
 'Kyurem',
 'Keldeo',
 'Meloetta',
 'Genesect',
 'Chespin',
 'Quilladin',
 'Chesnaught',
 'Fennekin',
 'Braixen',
 'Delphox',
 'Froakie',
 'Frogadier',
 'Greninja',
 'Bunnelby',
 'Diggersby',
 'Fletchling',
 'Fletchinder',
 'Talonflame',
 'Scatterbug',
 'Spewpa',
 'Vivillon',
 'Litleo',
 'Pyroar',
 'Flabébé',
 'Floette',
 'Florges',
 'Skiddo',
 'Gogoat',
 'Pancham',
 'Pangoro',
 'Furfrou',
 'Espurr',
 'Meowstic',
 'Honedge',
 'Doublade',
 'Aegislash',
 'Spritzee',
 'Aromatisse',
 'Swirlix',
 'Slurpuff',
 'Inkay',
 'Malamar',
 'Binacle',
 'Barbaracle',
 'Skrelp',
 'Dragalge',
 'Clauncher',
 'Clawitzer',
 'Helioptile',
 'Heliolisk',
 'Tyrunt',
 'Tyrantrum',
 'Amaura',
 'Aurorus',
 'Sylveon',
 'Hawlucha',
 'Dedenne',
 'Carbink',
 'Goomy',
 'Sliggoo',
 'Goodra',
 'Klefki',
 'Phantump',
 'Trevenant',
 'Pumpkaboo',
 'Gourgeist',
 'Bergmite',
 'Avalugg',
 'Noibat',
 'Noivern',
 'Xerneas',
 'Yveltal',
 'Zygarde',
 'Diancie',
 'Hoopa',
 'Volcanion']

In [55]:
# index'leri key, degerleri value olacak olan bir sozluk dondurur
dict(tempSeries)

{0: 'Bulbasaur',
 1: 'Ivysaur',
 2: 'Venusaur',
 3: 'Charmander',
 4: 'Charmeleon',
 5: 'Charizard',
 6: 'Squirtle',
 7: 'Wartortle',
 8: 'Blastoise',
 9: 'Caterpie',
 10: 'Metapod',
 11: 'Butterfree',
 12: 'Weedle',
 13: 'Kakuna',
 14: 'Beedrill',
 15: 'Pidgey',
 16: 'Pidgeotto',
 17: 'Pidgeot',
 18: 'Rattata',
 19: 'Raticate',
 20: 'Spearow',
 21: 'Fearow',
 22: 'Ekans',
 23: 'Arbok',
 24: 'Pikachu',
 25: 'Raichu',
 26: 'Sandshrew',
 27: 'Sandslash',
 28: 'Nidoran',
 29: 'Nidorina',
 30: 'Nidoqueen',
 31: 'Nidoran♂',
 32: 'Nidorino',
 33: 'Nidoking',
 34: 'Clefairy',
 35: 'Clefable',
 36: 'Vulpix',
 37: 'Ninetales',
 38: 'Jigglypuff',
 39: 'Wigglytuff',
 40: 'Zubat',
 41: 'Golbat',
 42: 'Oddish',
 43: 'Gloom',
 44: 'Vileplume',
 45: 'Paras',
 46: 'Parasect',
 47: 'Venonat',
 48: 'Venomoth',
 49: 'Diglett',
 50: 'Dugtrio',
 51: 'Meowth',
 52: 'Persian',
 53: 'Psyduck',
 54: 'Golduck',
 55: 'Mankey',
 56: 'Primeape',
 57: 'Growlithe',
 58: 'Arcanine',
 59: 'Poliwag',
 60: 'Poliwhirl',
 61: 'Poliwrath',
 62: 'Abra',
 63: 'Kadabra',
 64: 'Alakazam',
 65: 'Machop',
 66: 'Machoke',
 67: 'Machamp',
 68: 'Bellsprout',
 69: 'Weepinbell',
 70: 'Victreebel',
 71: 'Tentacool',
 72: 'Tentacruel',
 73: 'Geodude',
 74: 'Graveler',
 75: 'Golem',
 76: 'Ponyta',
 77: 'Rapidash',
 78: 'Slowpoke',
 79: 'Slowbro',
 80: 'Magnemite',
 81: 'Magneton',
 82: "Farfetch'd",
 83: 'Doduo',
 84: 'Dodrio',
 85: 'Seel',
 86: 'Dewgong',
 87: 'Grimer',
 88: 'Muk',
 89: 'Shellder',
 90: 'Cloyster',
 91: 'Gastly',
 92: 'Haunter',
 93: 'Gengar',
 94: 'Onix',
 95: 'Drowzee',
 96: 'Hypno',
 97: 'Krabby',
 98: 'Kingler',
 99: 'Voltorb',
 100: 'Electrode',
 101: 'Exeggcute',
 102: 'Exeggutor',
 103: 'Cubone',
 104: 'Marowak',
 105: 'Hitmonlee',
 106: 'Hitmonchan',
 107: 'Lickitung',
 108: 'Koffing',
 109: 'Weezing',
 110: 'Rhyhorn',
 111: 'Rhydon',
 112: 'Chansey',
 113: 'Tangela',
 114: 'Kangaskhan',
 115: 'Horsea',
 116: 'Seadra',
 117: 'Goldeen',
 118: 'Seaking',
 119: 'Staryu',
 120: 'Starmie',
 121: 'Mr. Mime',
 122: 'Scyther',
 123: 'Jynx',
 124: 'Electabuzz',
 125: 'Magmar',
 126: 'Pinsir',
 127: 'Tauros',
 128: 'Magikarp',
 129: 'Gyarados',
 130: 'Lapras',
 131: 'Ditto',
 132: 'Eevee',
 133: 'Vaporeon',
 134: 'Jolteon',
 135: 'Flareon',
 136: 'Porygon',
 137: 'Omanyte',
 138: 'Omastar',
 139: 'Kabuto',
 140: 'Kabutops',
 141: 'Aerodactyl',
 142: 'Snorlax',
 143: 'Articuno',
 144: 'Zapdos',
 145: 'Moltres',
 146: 'Dratini',
 147: 'Dragonair',
 148: 'Dragonite',
 149: 'Mewtwo',
 150: 'Mew',
 151: 'Chikorita',
 152: 'Bayleef',
 153: 'Meganium',
 154: 'Cyndaquil',
 155: 'Quilava',
 156: 'Typhlosion',
 157: 'Totodile',
 158: 'Croconaw',
 159: 'Feraligatr',
 160: 'Sentret',
 161: 'Furret',
 162: 'Hoothoot',
 163: 'Noctowl',
 164: 'Ledyba',
 165: 'Ledian',
 166: 'Spinarak',
 167: 'Ariados',
 168: 'Crobat',
 169: 'Chinchou',
 170: 'Lanturn',
 171: 'Pichu',
 172: 'Cleffa',
 173: 'Igglybuff',
 174: 'Togepi',
 175: 'Togetic',
 176: 'Natu',
 177: 'Xatu',
 178: 'Mareep',
 179: 'Flaaffy',
 180: 'Ampharos',
 181: 'Bellossom',
 182: 'Marill',
 183: 'Azumarill',
 184: 'Sudowoodo',
 185: 'Politoed',
 186: 'Hoppip',
 187: 'Skiploom',
 188: 'Jumpluff',
 189: 'Aipom',
 190: 'Sunkern',
 191: 'Sunflora',
 192: 'Yanma',
 193: 'Wooper',
 194: 'Quagsire',
 195: 'Espeon',
 196: 'Umbreon',
 197: 'Murkrow',
 198: 'Slowking',
 199: 'Misdreavus',
 200: 'Unown',
 201: 'Wobbuffet',
 202: 'Girafarig',
 203: 'Pineco',
 204: 'Forretress',
 205: 'Dunsparce',
 206: 'Gligar',
 207: 'Steelix',
 208: 'Snubbull',
 209: 'Granbull',
 210: 'Qwilfish',
 211: 'Scizor',
 212: 'Shuckle',
 213: 'Heracross',
 214: 'Sneasel',
 215: 'Teddiursa',
 216: 'Ursaring',
 217: 'Slugma',
 218: 'Magcargo',
 219: 'Swinub',
 220: 'Piloswine',
 221: 'Corsola',
 222: 'Remoraid',
 223: 'Octillery',
 224: 'Delibird',
 225: 'Mantine',
 226: 'Skarmory',
 227: 'Houndour',
 228: 'Houndoom',
 229: 'Kingdra',
 230: 'Phanpy',
 231: 'Donphan',
 232: 'Porygon2',
 233: 'Stantler',
 234: 'Smeargle',
 235: 'Tyrogue',
 236: 'Hitmontop',
 237: 'Smoochum',
 238: 'Elekid',
 239: 'Magby',
 240: 'Miltank',
 241: 'Blissey',
 242: 'Raikou',
 243: 'Entei',
 244: 'Suicune',
 245: 'Larvitar',
 246: 'Pupitar',
 247: 'Tyranitar',
 248: 'Lugia',
 249: 'Ho-oh',
 250: 'Celebi',
 251: 'Treecko',
 252: 'Grovyle',
 253: 'Sceptile',
 254: 'Torchic',
 255: 'Combusken',
 256: 'Blaziken',
 257: 'Mudkip',
 258: 'Marshtomp',
 259: 'Swampert',
 260: 'Poochyena',
 261: 'Mightyena',
 262: 'Zigzagoon',
 263: 'Linoone',
 264: 'Wurmple',
 265: 'Silcoon',
 266: 'Beautifly',
 267: 'Cascoon',
 268: 'Dustox',
 269: 'Lotad',
 270: 'Lombre',
 271: 'Ludicolo',
 272: 'Seedot',
 273: 'Nuzleaf',
 274: 'Shiftry',
 275: 'Taillow',
 276: 'Swellow',
 277: 'Wingull',
 278: 'Pelipper',
 279: 'Ralts',
 280: 'Kirlia',
 281: 'Gardevoir',
 282: 'Surskit',
 283: 'Masquerain',
 284: 'Shroomish',
 285: 'Breloom',
 286: 'Slakoth',
 287: 'Vigoroth',
 288: 'Slaking',
 289: 'Nincada',
 290: 'Ninjask',
 291: 'Shedinja',
 292: 'Whismur',
 293: 'Loudred',
 294: 'Exploud',
 295: 'Makuhita',
 296: 'Hariyama',
 297: 'Azurill',
 298: 'Nosepass',
 299: 'Skitty',
 300: 'Delcatty',
 301: 'Sableye',
 302: 'Mawile',
 303: 'Aron',
 304: 'Lairon',
 305: 'Aggron',
 306: 'Meditite',
 307: 'Medicham',
 308: 'Electrike',
 309: 'Manectric',
 310: 'Plusle',
 311: 'Minun',
 312: 'Volbeat',
 313: 'Illumise',
 314: 'Roselia',
 315: 'Gulpin',
 316: 'Swalot',
 317: 'Carvanha',
 318: 'Sharpedo',
 319: 'Wailmer',
 320: 'Wailord',
 321: 'Numel',
 322: 'Camerupt',
 323: 'Torkoal',
 324: 'Spoink',
 325: 'Grumpig',
 326: 'Spinda',
 327: 'Trapinch',
 328: 'Vibrava',
 329: 'Flygon',
 330: 'Cacnea',
 331: 'Cacturne',
 332: 'Swablu',
 333: 'Altaria',
 334: 'Zangoose',
 335: 'Seviper',
 336: 'Lunatone',
 337: 'Solrock',
 338: 'Barboach',
 339: 'Whiscash',
 340: 'Corphish',
 341: 'Crawdaunt',
 342: 'Baltoy',
 343: 'Claydol',
 344: 'Lileep',
 345: 'Cradily',
 346: 'Anorith',
 347: 'Armaldo',
 348: 'Feebas',
 349: 'Milotic',
 350: 'Castform',
 351: 'Kecleon',
 352: 'Shuppet',
 353: 'Banette',
 354: 'Duskull',
 355: 'Dusclops',
 356: 'Tropius',
 357: 'Chimecho',
 358: 'Absol',
 359: 'Wynaut',
 360: 'Snorunt',
 361: 'Glalie',
 362: 'Spheal',
 363: 'Sealeo',
 364: 'Walrein',
 365: 'Clamperl',
 366: 'Huntail',
 367: 'Gorebyss',
 368: 'Relicanth',
 369: 'Luvdisc',
 370: 'Bagon',
 371: 'Shelgon',
 372: 'Salamence',
 373: 'Beldum',
 374: 'Metang',
 375: 'Metagross',
 376: 'Regirock',
 377: 'Regice',
 378: 'Registeel',
 379: 'Latias',
 380: 'Latios',
 381: 'Kyogre',
 382: 'Groudon',
 383: 'Rayquaza',
 384: 'Jirachi',
 385: 'Deoxys',
 386: 'Turtwig',
 387: 'Grotle',
 388: 'Torterra',
 389: 'Chimchar',
 390: 'Monferno',
 391: 'Infernape',
 392: 'Piplup',
 393: 'Prinplup',
 394: 'Empoleon',
 395: 'Starly',
 396: 'Staravia',
 397: 'Staraptor',
 398: 'Bidoof',
 399: 'Bibarel',
 400: 'Kricketot',
 401: 'Kricketune',
 402: 'Shinx',
 403: 'Luxio',
 404: 'Luxray',
 405: 'Budew',
 406: 'Roserade',
 407: 'Cranidos',
 408: 'Rampardos',
 409: 'Shieldon',
 410: 'Bastiodon',
 411: 'Burmy',
 412: 'Wormadam',
 413: 'Mothim',
 414: 'Combee',
 415: 'Vespiquen',
 416: 'Pachirisu',
 417: 'Buizel',
 418: 'Floatzel',
 419: 'Cherubi',
 420: 'Cherrim',
 421: 'Shellos',
 422: 'Gastrodon',
 423: 'Ambipom',
 424: 'Drifloon',
 425: 'Drifblim',
 426: 'Buneary',
 427: 'Lopunny',
 428: 'Mismagius',
 429: 'Honchkrow',
 430: 'Glameow',
 431: 'Purugly',
 432: 'Chingling',
 433: 'Stunky',
 434: 'Skuntank',
 435: 'Bronzor',
 436: 'Bronzong',
 437: 'Bonsly',
 438: 'Mime Jr.',
 439: 'Happiny',
 440: 'Chatot',
 441: 'Spiritomb',
 442: 'Gible',
 443: 'Gabite',
 444: 'Garchomp',
 445: 'Munchlax',
 446: 'Riolu',
 447: 'Lucario',
 448: 'Hippopotas',
 449: 'Hippowdon',
 450: 'Skorupi',
 451: 'Drapion',
 452: 'Croagunk',
 453: 'Toxicroak',
 454: 'Carnivine',
 455: 'Finneon',
 456: 'Lumineon',
 457: 'Mantyke',
 458: 'Snover',
 459: 'Abomasnow',
 460: 'Weavile',
 461: 'Magnezone',
 462: 'Lickilicky',
 463: 'Rhyperior',
 464: 'Tangrowth',
 465: 'Electivire',
 466: 'Magmortar',
 467: 'Togekiss',
 468: 'Yanmega',
 469: 'Leafeon',
 470: 'Glaceon',
 471: 'Gliscor',
 472: 'Mamoswine',
 473: 'Porygon-Z',
 474: 'Gallade',
 475: 'Probopass',
 476: 'Dusknoir',
 477: 'Froslass',
 478: 'Rotom',
 479: 'Uxie',
 480: 'Mesprit',
 481: 'Azelf',
 482: 'Dialga',
 483: 'Palkia',
 484: 'Heatran',
 485: 'Regigigas',
 486: 'Giratina',
 487: 'Cresselia',
 488: 'Phione',
 489: 'Manaphy',
 490: 'Darkrai',
 491: 'Shaymin',
 492: 'Arceus',
 493: 'Victini',
 494: 'Snivy',
 495: 'Servine',
 496: 'Serperior',
 497: 'Tepig',
 498: 'Pignite',
 499: 'Emboar',
 500: 'Oshawott',
 501: 'Dewott',
 502: 'Samurott',
 503: 'Patrat',
 504: 'Watchog',
 505: 'Lillipup',
 506: 'Herdier',
 507: 'Stoutland',
 508: 'Purrloin',
 509: 'Liepard',
 510: 'Pansage',
 511: 'Simisage',
 512: 'Pansear',
 513: 'Simisear',
 514: 'Panpour',
 515: 'Simipour',
 516: 'Munna',
 517: 'Musharna',
 518: 'Pidove',
 519: 'Tranquill',
 520: 'Unfezant',
 521: 'Blitzle',
 522: 'Zebstrika',
 523: 'Roggenrola',
 524: 'Boldore',
 525: 'Gigalith',
 526: 'Woobat',
 527: 'Swoobat',
 528: 'Drilbur',
 529: 'Excadrill',
 530: 'Audino',
 531: 'Timburr',
 532: 'Gurdurr',
 533: 'Conkeldurr',
 534: 'Tympole',
 535: 'Palpitoad',
 536: 'Seismitoad',
 537: 'Throh',
 538: 'Sawk',
 539: 'Sewaddle',
 540: 'Swadloon',
 541: 'Leavanny',
 542: 'Venipede',
 543: 'Whirlipede',
 544: 'Scolipede',
 545: 'Cottonee',
 546: 'Whimsicott',
 547: 'Petilil',
 548: 'Lilligant',
 549: 'Basculin',
 550: 'Sandile',
 551: 'Krokorok',
 552: 'Krookodile',
 553: 'Darumaka',
 554: 'Darmanitan',
 555: 'Maractus',
 556: 'Dwebble',
 557: 'Crustle',
 558: 'Scraggy',
 559: 'Scrafty',
 560: 'Sigilyph',
 561: 'Yamask',
 562: 'Cofagrigus',
 563: 'Tirtouga',
 564: 'Carracosta',
 565: 'Archen',
 566: 'Archeops',
 567: 'Trubbish',
 568: 'Garbodor',
 569: 'Zorua',
 570: 'Zoroark',
 571: 'Minccino',
 572: 'Cinccino',
 573: 'Gothita',
 574: 'Gothorita',
 575: 'Gothitelle',
 576: 'Solosis',
 577: 'Duosion',
 578: 'Reuniclus',
 579: 'Ducklett',
 580: 'Swanna',
 581: 'Vanillite',
 582: 'Vanillish',
 583: 'Vanilluxe',
 584: 'Deerling',
 585: 'Sawsbuck',
 586: 'Emolga',
 587: 'Karrablast',
 588: 'Escavalier',
 589: 'Foongus',
 590: 'Amoonguss',
 591: 'Frillish',
 592: 'Jellicent',
 593: 'Alomomola',
 594: 'Joltik',
 595: 'Galvantula',
 596: 'Ferroseed',
 597: 'Ferrothorn',
 598: 'Klink',
 599: 'Klang',
 600: 'Klinklang',
 601: 'Tynamo',
 602: 'Eelektrik',
 603: 'Eelektross',
 604: 'Elgyem',
 605: 'Beheeyem',
 606: 'Litwick',
 607: 'Lampent',
 608: 'Chandelure',
 609: 'Axew',
 610: 'Fraxure',
 611: 'Haxorus',
 612: 'Cubchoo',
 613: 'Beartic',
 614: 'Cryogonal',
 615: 'Shelmet',
 616: 'Accelgor',
 617: 'Stunfisk',
 618: 'Mienfoo',
 619: 'Mienshao',
 620: 'Druddigon',
 621: 'Golett',
 622: 'Golurk',
 623: 'Pawniard',
 624: 'Bisharp',
 625: 'Bouffalant',
 626: 'Rufflet',
 627: 'Braviary',
 628: 'Vullaby',
 629: 'Mandibuzz',
 630: 'Heatmor',
 631: 'Durant',
 632: 'Deino',
 633: 'Zweilous',
 634: 'Hydreigon',
 635: 'Larvesta',
 636: 'Volcarona',
 637: 'Cobalion',
 638: 'Terrakion',
 639: 'Virizion',
 640: 'Tornadus',
 641: 'Thundurus',
 642: 'Reshiram',
 643: 'Zekrom',
 644: 'Landorus',
 645: 'Kyurem',
 646: 'Keldeo',
 647: 'Meloetta',
 648: 'Genesect',
 649: 'Chespin',
 650: 'Quilladin',
 651: 'Chesnaught',
 652: 'Fennekin',
 653: 'Braixen',
 654: 'Delphox',
 655: 'Froakie',
 656: 'Frogadier',
 657: 'Greninja',
 658: 'Bunnelby',
 659: 'Diggersby',
 660: 'Fletchling',
 661: 'Fletchinder',
 662: 'Talonflame',
 663: 'Scatterbug',
 664: 'Spewpa',
 665: 'Vivillon',
 666: 'Litleo',
 667: 'Pyroar',
 668: 'Flabébé',
 669: 'Floette',
 670: 'Florges',
 671: 'Skiddo',
 672: 'Gogoat',
 673: 'Pancham',
 674: 'Pangoro',
 675: 'Furfrou',
 676: 'Espurr',
 677: 'Meowstic',
 678: 'Honedge',
 679: 'Doublade',
 680: 'Aegislash',
 681: 'Spritzee',
 682: 'Aromatisse',
 683: 'Swirlix',
 684: 'Slurpuff',
 685: 'Inkay',
 686: 'Malamar',
 687: 'Binacle',
 688: 'Barbaracle',
 689: 'Skrelp',
 690: 'Dragalge',
 691: 'Clauncher',
 692: 'Clawitzer',
 693: 'Helioptile',
 694: 'Heliolisk',
 695: 'Tyrunt',
 696: 'Tyrantrum',
 697: 'Amaura',
 698: 'Aurorus',
 699: 'Sylveon',
 700: 'Hawlucha',
 701: 'Dedenne',
 702: 'Carbink',
 703: 'Goomy',
 704: 'Sliggoo',
 705: 'Goodra',
 706: 'Klefki',
 707: 'Phantump',
 708: 'Trevenant',
 709: 'Pumpkaboo',
 710: 'Gourgeist',
 711: 'Bergmite',
 712: 'Avalugg',
 713: 'Noibat',
 714: 'Noivern',
 715: 'Xerneas',
 716: 'Yveltal',
 717: 'Zygarde',
 718: 'Diancie',
 719: 'Hoopa',
 720: 'Volcanion'}

In [56]:
# maksimum elemanini dondurur
max(tempSeries)

'Zygarde'

In [57]:
# minimum elemanini dondurur
min(tempSeries)

'Abomasnow'

In [58]:
# series'i elemanlarina gore siralanmis yeni bir series dondurur
tempSeries.sort_values()

459    Abomasnow
62          Abra
358        Absol
616     Accelgor
680    Aegislash
         ...
570      Zoroark
569        Zorua
40         Zubat
633     Zweilous
717      Zygarde
Name: Pokemon, Length: 721, dtype: object

In [125]:
# series'in elemanlarina gore siralanmis yeni bir series dondurur
tempSeries.sort_values(ascending=False)

Pokemon
Wooper        Water
Slowbro       Water
Seismitoad    Water
Palpitoad     Water
Tympole       Water
              ...
Paras           Bug
Joltik          Bug
Larvesta        Bug
Karrablast      Bug
Shelmet         Bug
Name: Type, Length: 721, dtype: object

In [66]:
# csv dosyasindaki Pokemon column'unu index column olarak kullanacagi bir dataframe dondurur
tempDataFrame = pd.read_csv('resources\pokemon.csv', index_col='Pokemon') 
tempDataFrame

               Type
Pokemon
Bulbasaur     Grass
Ivysaur       Grass
Venusaur      Grass
Charmander     Fire
Charmeleon     Fire
...             ...
Yveltal        Dark
Zygarde      Dragon
Diancie        Rock
Hoopa       Psychic
Volcanion      Fire

[721 rows x 1 columns]

In [69]:
# indexleri indexlerine ve ilk column'u degerlerine esit olan bir series dondurur
tempSeries = tempDataFrame.squeeze('columns')
tempSeries

Pokemon
Bulbasaur       Grass
Ivysaur         Grass
Venusaur        Grass
Charmander       Fire
Charmeleon       Fire
               ...
Yveltal          Dark
Zygarde        Dragon
Diancie          Rock
Hoopa         Psychic
Volcanion        Fire
Name: Type, Length: 721, dtype: object

In [73]:
# sorgulanan degerin series'in indexleri arasinda olup olmadigin gosteren bir boolean dondurur
'Bulbasaur' in tempSeries

True

In [77]:
# tempSeries indexlerinden olusan yeni bir Index nesnesi dondurur
# yeni series'in indexleri sifirdan baslar
tempSeries.index

Index(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon',
       'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie',
       ...
       'Bergmite', 'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde', 'Diancie', 'Hoopa', 'Volcanion'],
      dtype='object', name='Pokemon', length=721)

In [78]:
# series elemanlarina ulasmak icin series[index_value] sytnax'ini kullaniriz
tempSeries['Bulbasaur']

'Grass'

In [82]:
# ayni anda birden fazla elemana ulasmak icin series[[index_value1, index_value2, ...]] syntax'ini kullaniriz
# bu, aranan degerlerin value, arattigimiz index'lerin yine index'ler oldugu bir series dondurur
tempSeries[['Bulbasaur', 'Noibat']]

Pokemon
Bulbasaur     Grass
Noibat       Flying
Name: Type, dtype: object

In [100]:
# python listelerinde yapabildigimiz slicing islemini series'in indexlerini kullanarak series uzerinde de yapabiliriz
tempSeries['Squirtle':'Noibat']
tempSeries[:'Noibat']
tempSeries[:'Noibat':10]

# series index'leri sayisal degerli ise index'lerin arasinda olmayan sayilar kullanarak elemanlara erismeye calisirsak hata aliriz
# cunku asagidaki gibi bir yazimda python -1'i index olarak kabul edip dogal olarak bulamazsa hata verecektir
tempSeries[-1]

# slicing isleminde negatif sayilari atlama degerini belirtmedigimiz surece kullanabiliriz 
# ornegin tempSeries[10:20:-1] bos bir series dondurecektir
tempSeries[-20:-1:2]

Pokemon
Dedenne      Electric
Goomy          Dragon
Goodra         Dragon
Phantump        Ghost
Pumpkaboo       Ghost
Bergmite          Ice
Noibat         Flying
Xerneas         Fairy
Zygarde        Dragon
Hoopa         Psychic
Name: Type, dtype: object

In [107]:
# series'deki bir elemana ulasmak icin get fonksiyonu ile index verebiliriz
tempSeries.get('Bulbasaur')

# series index'leri ne olursa olsun sifirdan baslayan index'ler ile de elemanlara erisebiliriz
tempSeries[0]
tempSeries.get(0)

'Grass'

In [108]:
# su islemle aynidir: tempSeries[['Bulbasaur', 'Noibat']]
# aranilan elemanlardan bir tanesini bile bulamazsa none dondurur
tempSeries.get(['Bulbasaur', 'Noibat'])

Pokemon
Bulbasaur     Grass
Noibat       Flying
Name: Type, dtype: object

In [109]:
# get fonksiyonuna ikinci parametre olarak, eger aradimiz degeri bulamazsa dondurecegi default degeri ayarlayabiliriz
tempSeries.get('Bulbasar', 'EMPTY')

'EMPTY'

In [111]:
tempSeries[0] = 'NEW POKEMON'
tempSeries['Bulbasaur'] = 'NEW POKEMON UPDATED'
tempSeries.head()

Pokemon
Bulbasaur     NEW POKEMON UPDATED
Ivysaur                     Grass
Venusaur                    Grass
Charmander                   Fire
Charmeleon                   Fire
Name: Type, dtype: object

In [114]:
tempSeries[['Bulbasaur', 'Ivysaur', 'Venusaur']] = ['NEW POKEMON 1', 'NEW POKEMON 2', 'NEW POKEMON 3']
tempSeries[[0, 1, 2]] = ['NEW POKEMON 4', 'NEW POKEMON 5', 'NEW POKEMON 6']
tempSeries

Pokemon
Bulbasaur     NEW POKEMON 4
Ivysaur       NEW POKEMON 5
Venusaur      NEW POKEMON 6
Charmander             Fire
Charmeleon             Fire
                  ...
Yveltal                Dark
Zygarde              Dragon
Diancie                Rock
Hoopa               Psychic
Volcanion              Fire
Name: Type, Length: 721, dtype: object

In [122]:
# bu kullanimda pokemonColumnSeries uzerinde yapilan degisiklikler pokemonDataFrame'deki ilgili degerleri de degistirir 
pokemonDataFrame = pd.read_csv("resources\pokemon.csv", usecols=["Pokemon"])

pokemonColumnSeries = pokemonDataFrame.squeeze("columns")

pokemonColumnSeries[2] = 'NEW POKEMON'

pokemonColumnSeries
pokemonDataFrame

         Pokemon
0      Bulbasaur
1        Ivysaur
2    NEW POKEMON
3     Charmander
4     Charmeleon
..           ...
716      Yveltal
717      Zygarde
718      Diancie
719        Hoopa
720    Volcanion

[721 rows x 1 columns]

In [123]:
# bu durumu onlemek istersek, islem yapmak istegimiz column'dan olusturdugumuz series'in kopyasinda islem yapmaliyiz
pokemonDataFrame = pd.read_csv("resources\pokemon.csv", usecols=["Pokemon"])

pokemonColumnSeries = pokemonDataFrame.squeeze("columns").copy()

pokemonColumnSeries[2] = 'NEW POKEMON'

pokemonColumnSeries
pokemonDataFrame

        Pokemon
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
..          ...
716     Yveltal
717     Zygarde
718     Diancie
719       Hoopa
720   Volcanion

[721 rows x 1 columns]

In [128]:
# series ile ilgili bilgileri gosterir
tempSeries.describe()

count       721
unique       21
top       Water
freq        105
Name: Type, dtype: object

In [135]:
# uygun series'ler ile aritmetik islemler yapabiliriz
# bu islemler sonucunde yapilan islemin her bir elemana uygulandigi yeni bir series dondurulur
tempSeries = pd.Series([1, 2, 3, 4, 5])

tempSeries + 10
tempSeries * 10
tempSeries / 5

0    0.2
1    0.4
2    0.6
3    0.8
4    1.0
dtype: float64

In [ ]:
# series elemanlarina 5 ekler ve bunu orijinal series uzerinde yapar
tempSeries.add(5)

In [140]:
# her bir degerden kac tane oldugunu gosteren bir series dondurur
# index degerleri, asil series'deki degerler ve value degerleri ise o series'de bunlardan kacar tane oldugu gosteren sayi olur
pokemonColumnSeries.value_counts()

Bulbasaur    1
Gallade      1
Dusknoir     1
Froslass     1
Rotom        1
            ..
Raikou       1
Entei        1
Suicune      1
Larvitar     1
Volcanion    1
Name: Pokemon, Length: 721, dtype: int64

In [142]:
# normalize parametresini True verirsek bu sefer elemanlardan kacar tane oldugunu degil,
# elemanlarin birbirlerinin sayisina gore oranini 0 - 1 araliginda verir
pokemonColumnSeries.value_counts(normalize=True)

# bunu 100 ile carparsak hangi degerden kacar tane oldununun yuzdelik oranini buluruz
pokemonColumnSeries.value_counts(normalize=True) * 100

Bulbasaur    0.138696
Gallade      0.138696
Dusknoir     0.138696
Froslass     0.138696
Rotom        0.138696
               ...
Raikou       0.138696
Entei        0.138696
Suicune      0.138696
Larvitar     0.138696
Volcanion    0.138696
Name: Pokemon, Length: 721, dtype: float64

In [ ]:
# dondurulen series'deki index'lerin siralanmasi icin sort parametresi True, orijinal sirasinda goruntulemek icin ise False veriririz
pokemonColumnSeries.value_counts(sort=True)

In [146]:
def addOne(value):
    return value + 1

# apply ile verilen fonksiyon, tum elemanlara uygulanarak degistirilmis elemanlardan olusan yeni bir series dondurur
tempSeries.apply(addOne)

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [149]:
def function(value):
    if('a' in value):
        return 'it has a letter'
    elif('b' in value):
        return 'it has b letter'
    else:
        return 'it doesn\'t have a or b letter'

# map metodu ile her bir elemana bir fonksiyon uygulayabiliriz
pokemonColumnSeries.map(function)

0                    it has a letter
1                    it has a letter
2      it doesn't have a or b letter
3                    it has a letter
4                    it has a letter
                   ...
716                  it has a letter
717                  it has a letter
718                  it has a letter
719                  it has a letter
720                  it has a letter
Name: Pokemon, Length: 721, dtype: object

In [155]:
mapping = {
    1 : 'bir',
    2 : 'iki',
    3 : 'uc',
    4 : 'dort',
    5 : 'bes'
}
# map fonksiyonu ile daha onceden tanimlagidimiz mapping'i uygulayabiliriz
# herhangi bir deger icin mapping belirtmezsek degerlerin hepsi NaN olacaktir
tempSeries.map(mapping)

0     bir
1     iki
2      uc
3    dort
4     bes
dtype: object